-- AlterTable
ALTER TABLE "SubTasks" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "isCompleted" SET DEFAULT false;

-- AlterTable
ALTER TABLE "Tasks" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
